### ISSUE TITLE
h = o * tf.tanh(x=self.c[-1]) in line no. 73 in network.py

### ISSUE THREAD

**Issue by leee222** [borelien/entailment-neural-attention-lstm-tf#3]
Hi, 

In network.py, (line no 73) 

> h = o*tf.tanh(x=self.c[-1])

 is correct? In the paper, `h` is derived by `o` and `c` which have the same timestamp, `t`.
It should be changed to `h = o*tf.tanh(c)`?

**Comment by borelien** [comment]
Yes you are right, good catch!
Fixed.
